### ISSUE TITLE
window.bearer_token no longer available

### ISSUE THREAD

**Issue by irritanterik** [matjaz/info.matjaz.candy#12]
Athom switched to a secure cookie for the window.bearer_token.
It's now retrieved by the set-cookie response header on `/api/manager/users/user/me`.

The bearer_token on the settings screen is now not prefilled on new installs.

**Comment by matjaz** [comment]
Not sure we can do anything. My Homey is a brick so when I'll have time I first need to unbrick Homey to see what we can do.

**Comment by bvdbos** [comment]
Did you manage to unbrick your Homey?

**Comment by matjaz** [comment]
No :( I guess I'll need to RMA.

**Comment by matjaz** [comment]
fixed in 0.7.7
