### ISSUE TITLE
[feature request] Actioncard for restarting a specific app

### ISSUE THREAD

**Issue by jghaanstra** [matjaz/info.matjaz.candy#14]
Since Homey firmware version 1.2.0 it's possible to restart apps. I'd like to see a "restart app" action card which allows you to select one of your installed apps and which restarts the app when executed.

**Comment by matjaz** [comment]
Added in 0.7.4 ac0df2972f383388d21121fa8367aa657a3d5150
Waiting for app store approval.

**Comment by jghaanstra** [comment]
Whoa, that's quick. Thanx!
