### ISSUE TITLE
Support for 1.3.x

### ISSUE THREAD

**Issue by sossienl** [matjaz/info.matjaz.candy#16]
I know I'm a bit fast with this, but seems like app is not compatible with (new) 1.3.0 rc7 release (experimental)

**Comment by matjaz** [comment]
Can you please test with 1.3 and create pull request? thanks!

**Comment by sossienl** [comment]
When cloning the project from GIT in OSX (Terminal) I get "Incompatible App version", see below.

info.matjaz.candy-master ***$ athom project --run
? Select active Homey: Homey @ ***.***.***.***:80
1/4 - Archiving...
2/4 - Uploading to Homey @ ***.***.***.***:80...
**incompatible_app_version**

**Comment by Inversion-NL** [comment]
Change compatibility": "1.2.x" to a higher number in app.json and test if it all works

**Comment by sossienl** [comment]
ok, running now

**Comment by TedTolboom** [comment]
created pull request #17 to update compatibility to be compatible with both 1.2 as well as 1.3

**Comment by matjaz** [comment]
merged
