### ISSUE TITLE
[Feature Request] Allow App Restart from App ID

### ISSUE THREAD

**Issue by Veldkornet** [matjaz/info.matjaz.candy#18]
Please make it possible to restart an application by App ID.

That way, if it detects that an app crashes, it can restart it (without having to make a new flow for every app that you have installed).

OR, otherwise add the Application Name as a source tag so that this can be used instead of the ID.

**Comment by matjaz** [comment]
2f9447fc9788b3422d2ed515e663f380b8c983b8
