### ISSUE TITLE
[Typo] Geen verbindingmet cloud

### ISSUE THREAD

**Issue by ghost** [matjaz/info.matjaz.candy#19]
Should be:
Geen verbinding met cloud

Mind the space between _verbinding_ and _met_

**Comment by matjaz** [comment]
It looks like text is ok. in English it's displayed with space. Can someone else confirm this issue? 
https://github.com/matjaz/info.matjaz.candy/blob/2f9447fc9788b3422d2ed515e663f380b8c983b8/app.json#L94

**Comment by ghost** [comment]
![verbindingmet](https://cloud.githubusercontent.com/assets/6205132/26398853/2fd43950-407b-11e7-9a39-41dbeaf14378.jpg)

See image above

**Comment by matjaz** [comment]
@DeefK please add information to issue reported to athom above. athombv/homey#1581

https://github.com/athombv/homey/blob/master/ISSUE_TEMPLATE.md
