### ISSUE TITLE
Flow not triggered when updated firmware

### ISSUE THREAD

**Issue by chrisboer** [matjaz/info.matjaz.candy#20]
![afbeelding](https://user-images.githubusercontent.com/23163409/28961894-33000494-7904-11e7-9cab-5adbaced5a6e.png)

**Comment by matjaz** [comment]
@irritanterik can you please take a look into this?

**Comment by matjaz** [comment]
I've looked into the issue. This feature was developed by @irritanterik 
It turns out card is triggered when new firmware is AVAILABLE not when already installed.
https://github.com/matjaz/info.matjaz.candy/blob/2f9447fc9788b3422d2ed515e663f380b8c983b8/lib/systemFlows.js#L32

**Comment by chrisboer** [comment]
Sorry but also did not receive any messages on new firmware

**Comment by chrisboer** [comment]
So not resolved
