### ISSUE TITLE
[Feature Request] Start/Stop App

### ISSUE THREAD

**Issue by rnldnkp** [matjaz/info.matjaz.candy#23]
Besides restarting an App. I would like to stop or start an App (disable/enable).

Use-case, there are multiple apps that don't have to run 24/7. I could stop day-apps at night and vice-versa. Single use apps could be started just in time, like a vacuum, sunshade, etc.

Goal is to preserve precious resources and make homey as fast as possible at each moment of day.

**Comment by matjaz** [comment]
added in 0.8.0. submitted for review in app store.
