### ISSUE TITLE
Error in flow card

### ISSUE THREAD

**Issue by DerKnutLord** [matjaz/info.matjaz.candy#26]
This problem Arises in the following flow cards:
Enable App
Disable App
Restart App
Enable All Folder Flows
Disable All Folder Flows
Value Updated in Last

![athom](https://user-images.githubusercontent.com/44134684/46915517-0f6e9f80-cfad-11e8-96ff-5c3b48e0c71f.jpg)

And the restart App by Id doesnt work also, with the error: no_auth_method_found

Candy: 0.8.0
Homey: 1.5.12

With Regards,
Knut

**Comment by irritanterik** [comment]
If still on Homey 1.5.*: Have you set up the bearer token in the settings screen?

**Comment by DerKnutLord** [comment]
Yeah, It stopped working at one time, but when I searched for a solution I
found that I had to enter a bearer token, sorry for being a n00b.

With kind regards,
René

Op wo 2 jan. 2019 19:04 schreef Erik van Dongen <notifications@github.com:

**Comment by irritanterik** [comment]
No problem. Can you close this issue then?

**Comment by DerKnutLord** [comment]
Yeah, I will, I'll put it on my agenda for tommorow.

Op wo 2 jan. 2019 22:26 schreef Erik van Dongen <notifications@github.com:
