### ISSUE TITLE
More colorful image

### ISSUE THREAD

**Issue by WeeJeWel** [matjaz/info.matjaz.candy#8]
With the new App Store, it's a shame to have these grayscale images.

I propose this image (royalty free):

![candy-956555_1920](https://cloud.githubusercontent.com/assets/319873/19483232/f98a10ea-9553-11e6-94ea-850a73886007.jpg)

:-)

**Comment by matjaz** [comment]
resolved in 301793447b0a8c6adc3e4fec0a4ef80011a12be1

**Comment by WeeJeWel** [comment]
<3
